[package]
name = "wgmeeting_github_ircbot"
version = "0.2.3"
authors = ["L. David Baron <dbaron@dbaron.org>"]
build = "build.rs"

[dependencies]
log = "0.3.7"
env_logger = "0.4.2"
lazy_static = "0.2.8"
regex = "0.2.1"
hubcaps = "0.3.12"
hyper = "0.10.10"
hyper-native-tls = "0.2.2"
serde_json = "1.0.2"
diff = "0.1.10"

# Depend on IRC, but remove its optional openssl dependency, since
# irc.w3.org doesn't support SSL, and since it conflicts with the
# openssl dependency of hyper-native-tls.
[dependencies.irc]
version = "0.11.7"
default-features = false
features = ["ctcp", "encode"]
