[package]
name = "wgmeeting_github_ircbot"
version = "0.1.0"
authors = ["L. David Baron <dbaron@dbaron.org>"]

[dependencies]
log = "0.3.7"
env_logger = "0.4.2"
irc = "0.11.6"
github = "0.1.2"
lazy_static = "0.2.6"
regex = "0.2.1"
