# documentation at "rustfmt --config-help"
# documentation at https://github.com/rust-lang-nursery/rustfmt/blob/master/src/config.rs
error_on_line_overflow = false
wrap_comments = true
format_strings = true
normalize_comments = true

reorder_imports = true
reorder_imported_names = true

spaces_around_ranges = true
